// The MIT License
//
// Copyright (c) 2020 Temporal Technologies Inc.  All rights reserved.
//
// Copyright (c) 2020 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by protoc-gen-go-helpers. DO NOT EDIT.
package topactivity

import (
	"google.golang.org/protobuf/proto"
)

// Marshal an object of type State to the protobuf v3 wire format
func (val *State) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type State from the protobuf v3 wire format
func (val *State) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *State) Size() int {
	return proto.Size(val)
}

// Equal returns whether two State values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *State) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *State
	switch t := that.(type) {
	case *State:
		that1 = t
	case State:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type TopActivityTask to the protobuf v3 wire format
func (val *TopActivityTask) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type TopActivityTask from the protobuf v3 wire format
func (val *TopActivityTask) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *TopActivityTask) Size() int {
	return proto.Size(val)
}

// Equal returns whether two TopActivityTask values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *TopActivityTask) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *TopActivityTask
	switch t := that.(type) {
	case *TopActivityTask:
		that1 = t
	case TopActivityTask:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type TopActivityTimeoutTaskAttributes to the protobuf v3 wire format
func (val *TopActivityTimeoutTaskAttributes) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type TopActivityTimeoutTaskAttributes from the protobuf v3 wire format
func (val *TopActivityTimeoutTaskAttributes) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *TopActivityTimeoutTaskAttributes) Size() int {
	return proto.Size(val)
}

// Equal returns whether two TopActivityTimeoutTaskAttributes values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *TopActivityTimeoutTaskAttributes) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *TopActivityTimeoutTaskAttributes
	switch t := that.(type) {
	case *TopActivityTimeoutTaskAttributes:
		that1 = t
	case TopActivityTimeoutTaskAttributes:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}

// Marshal an object of type TopActivityRetryTaskAttributes to the protobuf v3 wire format
func (val *TopActivityRetryTaskAttributes) Marshal() ([]byte, error) {
	return proto.Marshal(val)
}

// Unmarshal an object of type TopActivityRetryTaskAttributes from the protobuf v3 wire format
func (val *TopActivityRetryTaskAttributes) Unmarshal(buf []byte) error {
	return proto.Unmarshal(buf, val)
}

// Size returns the size of the object, in bytes, once serialized
func (val *TopActivityRetryTaskAttributes) Size() int {
	return proto.Size(val)
}

// Equal returns whether two TopActivityRetryTaskAttributes values are equivalent by recursively
// comparing the message's fields.
// For more information see the documentation for
// https://pkg.go.dev/google.golang.org/protobuf/proto#Equal
func (this *TopActivityRetryTaskAttributes) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	var that1 *TopActivityRetryTaskAttributes
	switch t := that.(type) {
	case *TopActivityRetryTaskAttributes:
		that1 = t
	case TopActivityRetryTaskAttributes:
		that1 = &t
	default:
		return false
	}

	return proto.Equal(this, that1)
}
